### ISSUE TITLE
Fast deletion of vector of constraints for Utilities.AbstractModel

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1102]
There is not specialized implementation for the deletion of vector of constraints.
Because of this, deleting `n` constraints of the same type were there are `m` constraints in total is `O(n * m)` while it could be `O(m)`.
Here are the `O(m)` operations:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/525cf612602f48a77797ec5708349703ec3ea82d/src/Utilities/model.jl#L29
https://github.com/JuliaOpt/MathOptInterface.jl/blob/525cf612602f48a77797ec5708349703ec3ea82d/src/Utilities/model.jl#L562-L564
See https://discourse.julialang.org/t/jump-0-21-how-to-efficiently-delete-non-binding-constraints-in-an-lp/40650

**Comment by odow** [comment]
Just to update, the code has been refactored since this issue. But the missing
```Julia
MOI.delete(::AbstractModel, ::Vector{MOI.ConstraintIndex{F,S}})
```
method is still a performance problem.

**Comment by odow** [comment]
I think the author of the discourse post, in saying that "The latter approach, however, does not seem very efficient to me" was referring to the fact that the two-step approach of collating the constraints then deleting seemed inefficient, not the fact that deleting constraints from a model was slow.

Closing because this isn't a performance problem. Here's a worst-case benchmark, where we add and then delete `N` constraints:
```Julia
julia> using MathOptInterface

julia> const MOI = MathOptInterface
MathOptInterface

julia> function main(N)
           model = MOI.Utilities.Model{Float64}()
           x = MOI.add_variables(model, N)
           c = [
               MOI.add_constraint(
                   model, 
                   MOI.ScalarAffineFunction([MOI.ScalarAffineTerm(1.0, x[i])], 0.0), 
                   MOI.LessThan(sqrt(i)),
               ) for i in 1:N
           ]
           MOI.delete(model, c)
           return model
       end
main (generic function with 1 method)

julia> @time main(100);
  0.000072 seconds (871 allocations: 55.469 KiB)

julia> @time main(1_000);
  0.000462 seconds (8.58 k allocations: 502.406 KiB)

julia> @time main(10_000);
  0.006236 seconds (89.61 k allocations: 5.467 MiB)

julia> @time main(100_000);
  0.063311 seconds (899.63 k allocations: 49.929 MiB)
```

```julia
x = [10^i for i in 1:6]
y = [(start = time(); main(i); time() - start) for i in x]
Plots.plot(x, y; xscale = :log10, yscale = :log10) 
```

<img width="598" alt="image" src="https://user-images.githubusercontent.com/8177701/172752372-ac6003fa-3e0f-4ab7-8cd7-872f8b860091.png">

Seems pretty linear. We can revisit if someone complains. Deleting constraints isn't a common operation.
