### ISSUE TITLE
Adding more formats in FileFormats

### ISSUE THREAD

**Issue by AKS1996** [jump-dev/MathOptInterface.jl#1105]
There's a really nice collection of convex instances:
- http://qplib.zib.de/instances.html
- http://plato.asu.edu/sub/testcases.html
But they don't support the formats (except MPS in some cases) as those in [FileFormats](https://github.com/jump-dev/MathOptInterface.jl/tree/master/test/FileFormats)

supporting `mod` format would be great starting point, as there are many instances in `mod` format

**Comment by odow** [comment]
I don't see us supporting the full `.mod` syntax anytime soon. 

However, the models you link to in qplib utilize a _very_ minimal subset of AMPL syntax that should be easy to parse. Given the lack of generality, it's probably better to just write an external script to parse them, rather than adding support to FileFormats and claiming we support `.mod`.

**Comment by odow** [comment]
Closing because this doesn't seem actionable. Extra formats are nice to have, but they will require someone motivated enough to implement them. I don't think we need an issue to track.
