### ISSUE TITLE
modify_coefficient does not merge the coefficients of each variable

### ISSUE THREAD

**Issue by tomasfmg** [jump-dev/MathOptInterface.jl#1117]
When more than one coefficient is associated to a variable, Ipopt does not merge them (other solvers do). That makes it difficult to modify it afterwards.

```julia
model = Ipopt.Optimizer()

x = MOI.add_variables(model, 1)

c = [1.0, 1.0]

objective_function = MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(c, [x[1], x[1]]), 0.0)
MOI.set(model, MOI.ObjectiveFunction{MOI.ScalarAffineFunction{Float64}}() ,objective_function)
MOI.set(model, MOI.ObjectiveSense(), MOI.MAX_SENSE)
MOI.add_constraint(model, MOI.SingleVariable(x[1]), MOI.GreaterThan(0.0))
MOI.add_constraint(model, MOI.SingleVariable(x[1]), MOI.LessThan(1.0))

ftype = MOI.get(model, MOI.ObjectiveFunctionType())

MOI.optimize!(model)

MOI.get(model, MOI.ObjectiveValue())

post_opt = MOI.get(model, MOI.ObjectiveFunction{ftype}())
post_opt.terms

MOI.modify(model, MOI.ObjectiveFunction{ftype}(), MOI.ScalarCoefficientChange(MOI.VariableIndex(1), 5.0))

post_modify = MOI.get(model, MOI.ObjectiveFunction{ftype}())
post_modify.terms

MOI.optimize!(model)

MOI.get(model, MOI.ObjectiveValue())
```

**Comment by blegat** [comment]
Good catch, this is a bug in `modify_coefficient` in which we assume there are no duplicates.
We should modify it to work duplicate coefficients if needed.
We should fix both
https://github.com/jump-dev/MathOptInterface.jl/blob/26e0af44a254b545276b528298a390d34c378586/src/Utilities/functions.jl#L701
and
https://github.com/jump-dev/MathOptInterface.jl/blob/26e0af44a254b545276b528298a390d34c378586/src/Utilities/functions.jl#L727

For the first method, we only take the first term with the correct variable:
https://github.com/jump-dev/MathOptInterface.jl/blob/26e0af44a254b545276b528298a390d34c378586/src/Utilities/functions.jl#L703
and ignore the other terms with the same variables if there are any.
We should do a loop and:
* If we do not find any term with the variable, we push a new one
* If we find a first term we modify its coefficient to the new values
* If we find other terms, we push their index in `del` and at the end of the whole loop we do `deleteat!(terms, del)`.

For the second method, it's already doing a loop and keeping track of a list of elements to delete with `del` so we could have a simpler fix. We can maybe just copy `new_coefficients` (as we don't want to modify the one given by the user) and then once we modify the first term we write `new_coefficients[j][2] = 2` so that subsequent terms are deleted.
