### ISSUE TITLE
Shall we move part of Ipopt's MOI wrapper to a new MOI Utilities?

### ISSUE THREAD

**Issue by frapac** [jump-dev/MathOptInterface.jl#1169]
Reading this new PR: https://github.com/JuliaOpt/NLopt.jl/pull/150/
it looks like several packages are re-implementing Ipopt's MOI wrapper. A non-exhaustive list being
- NLopt.jl
- [Hiop.jl](https://github.com/exanauts/Hiop.jl/blob/master/src/MOI_wrapper.jl)
- [MadNLP.jl](https://github.com/sshin23/MadNLP.jl/blob/master/src/Interfaces/MOI_interface.jl)

I am wondering if at some point, it would make sense to implement the common parts of these different wrappers as a MOI `Utilities` (e.g. the part to plug the linear and quadratic expressions in the `MOI.AbstractNLPEvaluator`)? I think in the long term that would ease the maintenance of the aforementioned packages.

**Comment by mlubin** [comment]
I agree the code duplication isn't great, but we also have to be careful that any solution doesn't actually make the solver wrappers harder to read. Writing and reading MOI wrappers is already complex enough. We learned from LinQuadOptInterface that intermediate abstractions can make the wrappers harder to understand because they don't fully alleviate the need for working at the MOI level, so the wrapper has to deal with MOI and the intermediate level at the same time.

> I think in the long term that would ease the maintenance of the aforementioned packages.

What maintenance issues have been tied to borrowing the structure of Ipopt's MOI wrapper? I don't think any changes to the structure have been needed in the past two years.

**Comment by frapac** [comment]
I understand. The argument against intermediate abstractions is a good one. 
I don't have any maintenance issue in mind (I think the last issue on Ipopt's wrapper was the sign of the Hessian set to the opposite when we were maximizing, but it was fixed long time ago). The main point was to have more concise MOI wrapper for the different NLP optimizers. But the return of experience from LinQuadOptInterface is compelling, indeed.

**Comment by odow** [comment]
> We learned from LinQuadOptInterface that intermediate abstractions can make the wrappers harder to understand because they don't fully alleviate the need for working at the MOI level, so the wrapper has to deal with MOI and the intermediate level at the same time

:100: I'm vetoing intermediate abstractions.

**Comment by blegat** [comment]
The large amount of copy-paste should be resolved by https://github.com/jump-dev/MathOptInterface.jl/issues/846.
For instance, a lot of duplicate work is to rewrite linear and quadratic constraints as nonlinear ones: After the NLP rewrite, this will be done by bridges so we can just get rid of all this code.

**Comment by frapac** [comment]
Closing this issue in favor of #846
