### ISSUE TITLE
What's the current way of running unit tests on all solvers?

### ISSUE THREAD

**Issue by shadiakiki1986** [jump-dev/MathOptInterface.jl#1192]
I've recently been trying to contribute to MOI through its testing (eg #1186 #1189 #1191), where I learned that you put unit tests that can benefit all solvers into MOI and run them from the solvers. If I add a test, what's the current way of running all the solver tests again to check if the new test catches any bugs? For example, I added a unit  test for `add_constraint` in #1191 , and I'd like to run all solvers with this test to check if any solvers have bugs in their `add_constraint` implementation. My current method is just to `dev` a few solvers and run the tests for each, but that's sort of slow because it builds everything and runs all the tests, versus just running the specific test that I'm working on. Is there any "better practice" that's faster?

**Comment by odow** [comment]
@blegat can do this with https://github.com/blegat/SolverTests.

I'm going to close this issue since it isn't a bug in MathOptInterface. The [developer chatroom](https://jump.dev/pages/governance/#developer-chatroom) (https://gitter.im/JuliaOpt/JuMP-dev) is a good place for these sorts of questions.
