### ISSUE TITLE
set field of CleverDict

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1326]
Looking at the code of `CleverDict`, `set` is simply `eachindex(vector)` isn't it ?
I thought that when an index was deleted, `set` was updated but it seems we switch to Dict instead so we should either remove this `set` vector or decide to stay dense when an element is deleted.

**Comment by odow** [comment]
Can you elaborate?

https://github.com/jump-dev/MathOptInterface.jl/blob/22240f0d6447eac608ce556284da1b761b9d720f/src/Utilities/CleverDicts.jl#L219-L241

**Comment by blegat** [comment]
So we should have something like
```julia
function Base.delete!(c::CleverDict{K}, k::K) where {K} 
     if _is_dense(c) 
         delete!(c.set, chash(k))
    else
        delete!(c.dict, k) 
     end 
     return 
 end 
```

**Comment by odow** [comment]
Isn't that just moving the problem somewhere else?

**Comment by blegat** [comment]
The field is coming from `DenseDict` which has this feature and was merged into `CleverDict` in https://github.com/jump-dev/MathOptInterface.jl/pull/1142. If we remove `set` then what remains of `DenseDict` ? I guess we had use cases for `DenseDict`

**Comment by odow** [comment]
Ah. Yes all for removing `.set` then. I don't see any obvious reason that it is used for.

**Comment by joaquimg** [comment]
Also, since we are looking into performance. There might be a difference between dense and dense+contiguous.
This might lead to 3 modes, which can pay off if its simple enough.
Most use cases do not involve deletions, so having them extremely high performance would be important in such a basic operation.
A first deletion would switch from pure vector to vector+set and out of order addition would switch to dict.

**Comment by joaquimg** [comment]
Ok, maybe for now .set is not essential since we can iterate in a vector. I would say +1 for simplifying.

However, I would advocate that complexity should be added if it improves benchmarks meaningfully, as long as we can keep it transparent outside CleverDict. In other words, if we have benchmarks for which `.set` can be better used as @blegat said, I'd say we do it.

These dict operations are bottlenecks very frequently.

I also like identity mode. Happens a lot in copies. Might be a little tricky to preserve operations like iterating in the elements or checking if an element is there (`.set` could solve this).

**Comment by blegat** [comment]
Yes, I agree for an identity mode. This should be used most of the times now, even constraint indices are 1 to `n` now with `VectorOfConstraints`.
Creating the `IndexMap` is a significant part of the time in https://github.com/jump-dev/MathOptInterface.jl/pull/1287

**Comment by odow** [comment]
Okay. I looked into this issue. `.set` is needed if you initialize the CleverDict with space, but then only partially fill it before querying.

@joaquimg do we have a benchmark where resizing the `vector` if you add one-by-one is a bottleneck? Alternatively, we could just close this issue.

**Comment by joaquimg** [comment]
I don't have one now.
I have a plan to run a few benchmarks in the following weeks.
We can close this for now and maybe open other ones like the identity mapping @blegat commented.

**Comment by blegat** [comment]
Yes, let's close this one once we have opened the other ones
