### ISSUE TITLE
The need for copy_names

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1533]
`copy_to` has a `copy_names` argument:

https://github.com/jump-dev/MathOptInterface.jl/blob/b391731104a08630e4e4215c990458457a05680c/src/MathOptInterface.jl#L127-L135

This also leads to things like 

https://github.com/jump-dev/MathOptInterface.jl/blob/b391731104a08630e4e4215c990458457a05680c/src/MathOptInterface.jl#L98-L109

The conceptual understanding of when and why these are used is a bit confusing.

It was added here, without much explanation of why:
https://github.com/jump-dev/MathOptInterface.jl/pull/297

As far as I can tell, the reason this was added was because we want to add names to the cache of a CachingOptimizer but not the optimizer:
https://github.com/jump-dev/MathOptInterface.jl/blob/b391731104a08630e4e4215c990458457a05680c/src/Utilities/cachingoptimizer.jl#L192-L203
This leads to confusion:
https://github.com/jump-dev/MathOptInterface.jl/issues/1225
and supporting names is hard:
https://github.com/jump-dev/MathOptInterface.jl/issues/674

Why do we need `copy_names`? Can we just ask the optimizer if it supports names? And if so, shouldn't we set them? This would make optimizer errors much nicer instead of `C21 was infeasible`.

We already skip some attributes if they aren't supported, so why not copy?
https://github.com/jump-dev/MathOptInterface.jl/blob/f08c78cc776e36e92270d42912128543d131c025/src/Utilities/copy.jl#L151-L162

We should either:

 - Remove `copy_names`
 - Document why it is needed

**Comment by blegat** [comment]
IIRC, the reason is: In the context of `CachingOptimizer`, you don't want to copy names to the second layer even if it is supported for performance reason. I guess it's not specific to names but it applies to all attributes that are not needed for solving. However, if the optimizer is a file writer then it does not apply. Maybe dropping it silently if it is not supported is the right approach.

**Comment by odow** [comment]
> for performance reason

I guess we should benchmark this. I'd be surprised if this was an issue. In general, it makes a lot of sense to push names to the bottom solvers if they support it. 

Even for things like writing the model using Gurobi/CPLEX level file writers. Currently all the names are lost. There have been  a few issues on Discourse about this.

Same with debugging IIS. I know @jd-lara has complained to me about CPLEX losing this information and only reporting the column index that was the problem, not the name. I can't find the issue for it though. It may have just been on WhatsApp.

If the cost off setting names in the solver is a bottleneck, we're doing something wrong. We could also encourage solvers that don't natively support constraint names to not support them and just use a `CachingOptimizer` to store them.

Related issue in JuMP: https://github.com/jump-dev/JuMP.jl/issues/2655

I can see how this was complicated when we had names for variable constraints, but now that we don't a lot of the original motivations have gone.

**Comment by joaquimg** [comment]
Pushing names to xpress is prohibitive if you need performance.
I would guess it won't be the less performant in this sense since we have many open-source solvers.

**Comment by odow** [comment]
> Pushing names to xpress is prohibitive if you need performance.

You could have an option in `Xpress.Optimizer` to ignore names. 

It feels like making this decision at the JuMP/MOI/CachingOptimizer level is the wrong place because people have different needs.

**Comment by blegat** [comment]
> We could also encourage solvers that don't natively support constraint names to not support them and just use a CachingOptimizer to store them.

Yes, definitely.

> I can see how this was complicated when we had names for variable constraints, but now that we don't a lot of the original motivations have gone.

I agree, copying names for all variable bounds might also have been expensive.

> I would guess it won't be the less performant in this sense since we have many open-source solvers.

Which open source solver supports name ?

It seems copying names if supported might be a good default but people may want to be able to disable it as an option to JuMP and then the CachingOptimizer.
We could generalize the `filter` we already have.
The downside is that it might be a lot when you just want to filter constraints to also hve to implement a method for moddel attributes, variable attributes ,... 
So instead of passing a function, you would pass an object.
Then by default `copy_attribute`, `copy_constraints`, is true and you can implement methods to change this.
Another approach is for CachingOptimizer to wrap the cache in an MOi layer that filters out the names

**Comment by odow** [comment]
> but people may want to be able to disable it as an option ... [and the rest]

This is overly complicated. If @joaquimg wants to skip names in Xpress, he can add an option to `Xpress.Optimizer(copy_names = false)`.
