### ISSUE TITLE
Consider adding warning back to SquareBridge

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1899]
https://github.com/jump-dev/MathOptInterface.jl/pull/1891#discussion_r895236523

**Comment by blegat** [comment]
I don't remember exactly why I added it in https://github.com/jump-dev/MathOptInterface.jl/pull/522 and I can't find the trace since that PR description is quite empty.
I sort of remember discussing with @mlubin that the limit `1e-10` was quite arbitrary as it could have as well been, say `1e-8`, so we might as well give a warning in some range where we're unsure what to do. We could change `1e-8` but I think we should keep a range with a warning.

**Comment by odow** [comment]
Who does this help, and under what conditions?

**Comment by blegat** [comment]
If you have coefficients between `1e-8` and `1e-10`, it's unclear whether this should be symmetric or not so it's best we warn the user

**Comment by odow** [comment]
That's the literal interpretation. But in practice, how would this occur?

**Comment by odow** [comment]
It's also a dumb warning. The equality constraint might have a tolerance larger than 1e-8, so they might be different by more than 1e-8 even with the equality constraint. 

If we want to warn about non-symmetric PSD constraint at the JuMP level, that's one thing, but I don't think we need a warning at the bridge level.
