### ISSUE TITLE
Order-maintaining copy_to 

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/MathOptInterface.jl#2236]
It would be handy in some cases to have a second implementation of `copy_to` that adds variables (and constraints) in the order of increasing index instead of constrained and then free.

That way one can get rid of the `index_map`. Concretely, I'm working on non-linear on top of MOI with a function `f(x)` that takes the vector of variables in order of variable index. When copying the model, this would be handy to keep the same order to avoid having to call ` f(permutation_matrix * x)` all the time

**Comment by blegat** [comment]
I agree, when there is an NLP block then we simply disable constrained variables.
For https://github.com/JuliaManifolds/Manopt.jl/issues/273, we would need to maintain the order of variables but still use constrained variables.
So I think we should, if any part of the model is a black-box function, add constrained variables but without reordering.
We could also do like MIP callbacks and have a variable attribute to get the values so that it goes through the index map but for it to be efficient enough for NLP we might need the `CleverDict`t o have a special case when the order is the same

**Comment by matbesancon** [comment]
we could add a keyword argument `always_maintain_variable_order=false` to `default_copy_to`, and then:
```julia
maintain_variable_order = always_maintain_variable_order || has_nlp
```

**Comment by matbesancon** [comment]
The problem is if you want to set that as the caller of `copy_to`, and not at the Optimizer level

**Comment by blegat** [comment]
The approach then is to use a layer like here: https://github.com/jump-dev/MathOptInterface.jl/blob/dab02e5f2f9018c324bf251a46b41d4ccb86ac36/src/Utilities/copy.jl#L512-L643

**Comment by odow** [comment]
This actually hints at a deeper problem: the order of MOI constraints in a copy is not the same between solvers. One places this crops up is writing files like MPS. Most copies end up grouping by constraint type and then construction order, but I do wonder if there should instead be a global order of constraints. i.e., all `ConstraintIndex` must have a unique `.value::Int64` field, not just unique within their constraint type. That's a MOI 2.0 problem though.

**Comment by odow** [comment]
@blegat and I discussed this without much of a conclusion. Do we have a reproducible example of the current problem? Is it necessary to use a permutation matrix? Couldn't we just pass a (permuted) view of the vector to the function `x`?

Here's the bit where we disable constrained variables:

https://github.com/jump-dev/MathOptInterface.jl/blob/a049bfe997f9c3b2b31e6bdac40bce27d96534e0/src/Utilities/copy.jl#L488-L500

So maybe we do need a way for `dest` to opt-in to this. I think this is probably the only place where it matters? Because solver wrappers implementing `copy_to` have control over the order.

**Comment by matbesancon** [comment]
one solution would be a three-argument `copy_to` with default doing whatever the solver wants, and then other `copy_to` methods which add constraints, like keep variable / constraint order

**Comment by odow** [comment]
Keeping constraint order would require a big change to MOI. We're really just not set up to record or communicate that information. (It'd likely mean requiring implementations to use a non-decreasing UUID for `.value`, and plenty of implementations (ab)use the value field for all sorts of things.

Can you point to a concrete example where this is necessary?

This line in Boscia is worrying:
https://github.com/ZIB-IOL/Boscia.jl/blob/f47ce9c0c93081de3dc468ef2648401cedfa73f8/src/interface.jl#L101-L103
Nothing in MOI guarantees that variable `.value`s should be contiguous or `1` to `n`.

Can't you just work-around this with a permutation vector? Or ask your oracle to accept a `view`?

```julia
julia> x = [0.1, 0.2, 0.3, 0.4]
4-element Vector{Float64}:
 0.1
 0.2
 0.3
 0.4

julia> p = [4, 2, 1, 3]
4-element Vector{Int64}:
 4
 2
 1
 3

julia> x[p]
4-element Vector{Float64}:
 0.4
 0.2
 0.1
 0.3

julia> view(x, p)
4-element view(::Vector{Float64}, [4, 2, 1, 3]) with eltype Float64:
 0.4
 0.2
 0.1
 0.3
```

**Comment by blegat** [comment]
If you want indices to be from 1 to n you can use a MatrixOfConstraints. See Zaphod.jl for an example of how to use it

**Comment by odow** [comment]
I'd propose we close this. I don't think we need to add more complexity to MOI.

**Comment by odow** [comment]
Maybe we could add all constraints required a shared non-decreasing UUID as one of the MOI 2.0 decisions.

**Comment by odow** [comment]
Thoughts @matbesancon?

**Comment by matbesancon** [comment]
> If you want indices to be from 1 to n you can use a MatrixOfConstraints. See Zaphod.jl for an example of how to use it

I'll do that as a temporary solution, but the fact that the order-preserving implementation is right there in copy-to without being accessible is a bit frustrating
