### ISSUE TITLE
[FileFormats.MPS] another potential wrong result

### ISSUE THREAD

**Issue by foreverdyz** [jump-dev/MathOptInterface.jl#2479]
Expect for https://github.com/jump-dev/MathOptInterface.jl/issues/2469, we found that another model from MIPLIB called neos-4738912-atrato.mps generated a potential wrong result with Julia + Gurobi. We checked this file and found there was no "*".
There are two issues: first, the final obj of Julia + Gurobi is slightly different to Python GRB. Though the difference is small, but considering we are using the same solver and the GAP is 0, we still think there might be an issue. Second, why the runtime for Julia + Gurobi is doubled to Python GRB? We are using the same solver (Gurobi 10.0.1) and the same device.
Looks Julia + HiGHS generating the same obj to Julia + Gurobi, which are slightly different to the optimal obj from the MIPLIB website. Maybe it is another JuMP bug.
<img width="863" alt="julia1" src="https://github.com/jump-dev/Gurobi.jl/assets/44935367/b223a3ac-099e-4c4e-8fb1-0b386be4e1f5">
![julia2](https://github.com/jump-dev/Gurobi.jl/assets/44935367/c2b12558-0226-4f6a-86fe-bbff087f2413)
<img width="948" alt="python" src="https://github.com/jump-dev/Gurobi.jl/assets/44935367/7b6c0b1e-af09-44f1-872b-b75b24b603ef">
![highs](https://github.com/jump-dev/Gurobi.jl/assets/44935367/9015d787-e23b-4606-8e46-573e9a53cb91)

**Comment by odow** [comment]
Thanks, I'll take a look.

>  the final obj of Julia + Gurobi is slightly different to Python GRB

One cause might be that we don't preserve row order when reading from an MPS file in MOI.

It looks like presolve is different.

> Second, why the runtime for Julia + Gurobi is doubled to Python GRB

They're solving different models.

**Comment by odow** [comment]
Oh man.

<img width="1006" alt="image" src="https://github.com/jump-dev/MathOptInterface.jl/assets/8177701/d104d095-613a-4202-854b-eeb7668d7eec">

I hate this bloody format. There are so much implicit behavior.

So this is a bug. We're reading some variables as integer with free upper bound instead of `1`.

**Comment by odow** [comment]
Fix is https://github.com/jump-dev/MathOptInterface.jl/pull/2480

**Comment by foreverdyz** [comment]
Hi @odow 
Thank you. Now I just need to remove the older JuMP and install the new one, right?

**Comment by odow** [comment]
No, you need `] add MathOptInterface#master` (until I make a new release)

**Comment by foreverdyz** [comment]
Hi @odow,

Sorry to interrupt you again.

I tried ] add MathOptInterface#master; however, I found there was at least one wrong case in MIPLIB called supportcase6. The correct answer is 51906.47737 (https://miplib.zib.de/instance_details_supportcase6.html). However, both gurobi and highs returned infeasible.

<img width="840" alt="bug" src="https://github.com/jump-dev/MathOptInterface.jl/assets/44935367/1b124ac5-8e4d-4aff-a8fb-ab157d153127">

Could you take a look? Thanks a lot.

**Comment by odow** [comment]
My fix in #2480 wasn't quite correct. PR incoming

**Comment by odow** [comment]
Actually. There is some ambiguity.

The variable `I130051(1)` appears in between a `INTORG...INTEND` block. 

So per Gurobi "The variables introduced between a pair of markers must take integer values. All variables within markers will have a default lower bound of 0 and a default upper bound of 1 (other bounds can be specified in the BOUNDS section)."

Okay. So it is integer, and the default bounds are `[0, 1]`.

The only other place it appears is `LI BND1      I130051(1)  0` in the `BOUNDS` section, which says that the lower bound for the integer variable is `0`. This seems superfluous, because the default lower is `0`.

But I assume it _also_ means that the default upper is ignored?

Mosek say https://docs.mosek.com/latest/capi/mps-format.html

![image](https://github.com/jump-dev/MathOptInterface.jl/assets/8177701/8bbbe8dd-54f8-4752-97cd-0dea62283292)

So I would argue that this should still be `[0, 1]`, not `[0, Inf]`.

cc @simonbowly can you share any insight?

**Comment by simonbowly** [comment]
Ah, MPS, what fun.

> But I assume it also means that the default upper is ignored?

Yes, that's the convention Gurobi follows. Specifically: if a variable is in the INTORG section, it gets a default domain of `[0, 1]`. If there are *any* bounds specified later for that variable, the default domain reverts to `[0, inf]` (then the specified bounds are added on top of that).

So an integer variable in `[0, inf]` is by written to MPS as:

```
NAME
ROWS
 N  OBJ
COLUMNS
    MARKER    'MARKER'                 'INTORG'
    x         OBJ       0
    MARKER    'MARKER'                 'INTEND'
RHS
BOUNDS
 LI BND1      x         0
ENDATA
```

The [CPLEX docs](https://www.ibm.com/docs/en/icos/22.1.1?topic=extensions-integer-variables-in-mps-files) seem to be the only ones that make a slightly less ambiguous statement on the topic:

> If no bounds are specified for the variables within markers, bounds of 0 (zero) and 1 (one) are assumed.

**Comment by odow** [comment]
I hate this format.

FWIW, MOI **always** adds explicit `MI` or `PL` for unspecified bounds. No defaults.

https://github.com/jump-dev/MathOptInterface.jl/blob/eff2982a7632f710e32e5ce62b8c96393270b3b1/src/FileFormats/MPS/MPS.jl#L705-L717

**Comment by odow** [comment]
But also like. Why would you write `LI BND1      x         0` instead of `PL BND1      x`? Surely saying "the upper bound is infinity" is more important than "the lower bound is 0, and the upper bound implicitly depends on how you interpret our documentation".

**Comment by simonbowly** [comment]
I can only speculate. Seems to be an age-old convention passed down through the generations, given that CPLEX and HIGHS appear to follow the same approach. Maybe the difference between `PL x` to specify `[0, inf]` and `L1 x 1` to specify `[1, inf]` was considered too jarring at the time.

**Comment by odow** [comment]
> Seems to be an age-old convention passed down through the generations

We need a JuMP office at ZIB...
