### ISSUE TITLE
Add support for names in solver wrappers

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#674]
If I am not mistaken, LQOI add supports for names even if the solver does not support names.
It does not really match the MOI philosophy of not adding features on the wrapper if that does not rely on a support provided by the solver.
If we make an exception for names that means that all solver wrappers should implement names but that's unscalable.
One reason for LQOI to support names is that LQOI solvers `supports_default_copy_to` so support for names is the only thing missing to allow them to be used in direct mode without cache.
So should we say that all solver wrappers that `supports_default_copy_to` should implement names ? That's also probably unscalable to maintain.
Since implementation of names is always the same we could do one of the following:

1) Creates macros for adding the necessary fields in the optimizer struct and have an abstract type `AbstractOptimizerWithName` for optimizers with this field (or a trait maybe). Then we can implement names in MOI and there is no need to add a method for every implementation.
2) Add a MOI layer that adds support for names (it basically lets all MOI calls go through except the ones about names that it handles). It is kind of like UniversalFallback but only for names (you don't want to add an UniversalFallback on top of an optimizer since it will silently hide unsupported constraints, unsupported attributes, ...).

**Comment by mlubin** [comment]
Are you referring to lookup by name (name -> variable/constraint) or just name attributes?

I think all of the solvers that we want to use in direct mode support name attributes:
http://www.gurobi.com/documentation/8.1/refman/varname.html#attr:VarName
http://www.gurobi.com/documentation/8.1/refman/constrname.html#attr:ConstrName
https://www.ibm.com/support/knowledgecenter/SSSA5P_12.6.0/ilog.odms.cplex.help/CPLEX/GettingStarted/topics/tutorials/InteractiveOptimizer/displayingNames.html
https://community.fico.com/s/question/0D58000004ScRSkCAN/how-to-set-the-name-of-constraints-for-xpress-in-python

Furthermore we *should* be passing JuMP names down to the solvers so that names in error messages match up.

Lookup by name is more problematic at the native solver level. Gurobi supports this but the semantics don't match the MOI lookup rules; Gurobi returns an arbitrary variable/constraint back if multiple have the same name: https://www.gurobi.com/documentation/8.1/refman/c_grbgetvarbyname.html. If it's the case that *no* or very few solver natively support lookup by name in a way that's compatible with MOI, maybe we should drop this functionality from MOI and handle it at the JuMP level.

**Comment by odow** [comment]
I don't know if there is a need for this. Solvers can use a caching optimizer to store names.

**Comment by blegat** [comment]
Yes, let's close this. Wrappers shouldn't implement names if the solver does not
