### ISSUE TITLE
Update MOI.Test to support any coefficient that is a subtype of Real

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/MathOptInterface.jl#841]
Looking for an easy way to help contribute to MOI? 

Help us by updating the tests so that we can run them with a generic coefficient type, instead of just `Float64`.

## Problem

I am trying to test a solver that works on a `Model{T}` for any `T <: Real`, but I can only run the vast majority of tests when `T = Float64`.

## Solution 

Things have changed quite a lot since the discussion below. Here's the latest (August 2021):

Step 1: pick a file from https://github.com/jump-dev/MathOptInterface.jl/tree/master/src/Test

Step 2: pick a test which contains explicit `Float64`s. Here's one
https://github.com/jump-dev/MathOptInterface.jl/blob/f08c78cc776e36e92270d42912128543d131c025/src/Test/test_variable.jl#L180-L201

Step 3: rewrite it to use a type parameter `T` instead
```Julia
function test_variable_solve_with_upperbound(
    model::MOI.ModelLike,
    config::Config{T},
) where {T}
    x = MOI.add_variable(model)
    c1 = MOI.add_constraint(model, MOI.SingleVariable(x), MOI.LessThan(one(T)))
    @test x.value == c1.value
    c2 = MOI.add_constraint(model, MOI.SingleVariable(x), MOI.GreaterThan(zero(T)))
    @test x.value == c2.value
    f = MOI.ScalarAffineFunction([MOI.ScalarAffineTerm(T(2), x)], zero(T))
    MOI.set(model, MOI.ObjectiveFunction{typeof(f)}(), f)
    MOI.set(model, MOI.ObjectiveSense(), MOI.MAX_SENSE)
    _test_model_solution(
        model,
        config;
        objective_value = T(2),
        variable_primal = [(x, one(T))],
        constraint_primal = [(c1, one(T)), (c2, one(T))],
        constraint_dual = [(c1, -T(2)), (c2, zero(T))],
    )
    return
end
```

**Comment by ericphanson** [comment]
@jiazhengzhu and I would be interested in this too! Could someone point us to how to go about generalizing the tests?

**Comment by blegat** [comment]
It might also be a type parameter of `TestConfig` so that the types local variables of the test functions are known at compile time

**Comment by ericphanson** [comment]
In #855 some decisions were made about the details of doing this, and I think the following was more-or-less settled on for how to update a set of tests:

* Change one test file per PR
* Change test function signatures from `f(args, config::TestConfig)` to `f(args, config::TestConfig{T}) where T`
* Use `one(T)` and `zero(T)` to replace `1.0` and `0.0` as numeric entries in test problems
* Likewise, use `T(n)` to replace `n.0` (for integer `n`)
* Likewise, replace non-integer floats `x` by `T(m//n)` where `x == m/n`
* Add type parameters to `MOI.EqualTo`, `MOI.GreaterThan`, `MOI.LessThan` when used as types (but not as constructors), and to `MOI.ScalarAffineTerm`, `MOI.ScalarAffineFunction`, `MOI.VectorAffineTerm`, and `MOI.VectorAffineFunction`.
* Add spaces between elements of vectors, like `[one(T), zero(T)]` rather than `[one(T),zero(T)]`

This can be mostly done via find-and-replace. Slightly less obvious tricks:
* For "`T(n)` to replace `n.0`", this can be done with regex-find `(\d*?_?\d+?)\.0` and replace `T($1)`
* For finding constructors but not types, search for e.g. `MOI.EqualTo(` (with the parenthesis to only get constructors)
* For adding spaces between elements of vectors, regex-find `(\[.+?),([^ ])`, replace `$1, $2`, and repeat it until the file is invariant (since it adds only one space per vector per find-and-replace).

Tests to update:
- [x] `contlinear.jl` (#855)
- [ ] `contconic.jl`
- [ ] `contquadratic.jl`
- [ ] `intconic.jl`
- [ ] `intlinear.jl`
- [ ] `modellike.jl`
- [ ] `nlp.jl`

And unit tests. Maybe those will need a different treatment though? I'm not really sure.

After the tests are updated, the tests of the tests will need to be updated. These will (hopefully) not pass until the internal use of `Float64` numeric types in MOI are generalized, which should be done in separate PRs.

(Hope I got that all right, regarding the emergent plan).

**Comment by odow** [comment]
This sounds fantastic. Small incremental steps.

**Comment by mtanneau** [comment]
Is someone actively working on this? If not I may start to.

**Comment by ericphanson** [comment]
That would be great! I’m not actively working on it now, and I don’t think @jiazhengzhu is either, but I can’t speak for anyone else.

**Comment by odow** [comment]
We're cracking on with this #1667, #1668, #1669. But there are a loooooot of tests to go.

A simple search of `Float64` shows:
![image](https://user-images.githubusercontent.com/8177701/142557959-a002c467-765a-42b1-98aa-fab330290478.png)

**Comment by odow** [comment]
I have been making progress. After #1681, only the 7000 lines of conic tests remain...

**Comment by odow** [comment]
That was a pretty grinding few days, but it was faster than I thought it would be. 

We now run a standard `MOI.Test.runtests` with `BigFloat`:
https://github.com/jump-dev/MathOptInterface.jl/blob/bc0bf1b5b87ef409542326a9de2ce7d8f57ab671/test/Test/Test.jl#L52-L69
This runs. all the tests automatically, so it should catch us re-introducing `Float64`-specific tests.

Closing because I think this is now done. The next release of MOI should be of interest to:
 * Hypatia (cc @chriscoey @lkapelevich)
 * Tulip (cc @mtanneau)
 * COSMO (cc @migarstka)

**Comment by chriscoey** [comment]
Nice work @odow

**Comment by odow** [comment]
I can't promise I got every case, only that it works for BigFloat. For example, I think you'll run into a lot of issues if you use rational arithmetic, but that's probably to be expected because a lot of the tests don't have a rational solution. 

We could potentially come up with a clever rational check if its a problem. `@requires sqrt(T(2)) isa T`?
```Julia
julia> T = Rational{Int}
Rational{Int64}

julia> sqrt(T(2)) isa T
false

julia> T = BigFloat
BigFloat

julia> sqrt(T(2)) isa T
true
```

**Comment by chriscoey** [comment]
Hypatia doesn't really work with rationals anymore so we won't need that, not sure about Tulip or COSMO

**Comment by mtanneau** [comment]
> Hypatia doesn't really work with rationals anymore so we won't need that, not sure about Tulip or COSMO

Same, I dropped Rational a while ago, in part because of the type-instability, in part because of numerical issues (the required precision would quickly explode)

**Comment by chriscoey** [comment]
^ Hashtag relatable

**Comment by blegat** [comment]
CDDLib needs `Rational{BigInt}`
